### ISSUE TITLE
discriminated union regression between 1.0.9 and 1.3.0

### ISSUE THREAD

**Issue by 1st1** [vriad/zod#39]
The following schema

```typescript
export const CellResultsAPIValidator = z.union([
  z.object({
    kind: z.literal("error"),
    error: z.object({
      message: z.string(),
      type: z.string(),
    }),
  }),
  z.object({
    kind: z.literal("results"),
    results: z
      .array(
        z.union([
          z.object({
            kind: z.literal("data"),
            data: z.tuple([z.string(), z.string(), z.string()]),
          }),
          z.object({
            kind: z.literal("error"),
            error: z.tuple([z.string(), z.string(), z.object({})]),
          }),
          z.object({
            kind: z.literal("skipped"),
          }),
        ])
      )
      .nonempty(),
  }),
]);
```

no longer validates the following

```
{ Error: Type mismatch in union.
Received: {
  "kind": "results",
  "results": [
    {
      "kind": "error",
      "error": [
        "InvalidReferenceError",
        "object type or alias 'User' does not exist",
        {
          "65521": "7",
          "65522": "11",
          "65523": "1",
          "65524": "8"
        }
      ]
    }
  ]
}

Expected: object OR object
    at new ZodError (/Users/yury/dev/edge/tutorial/node_modules/zod/lib/src/ZodError.js:20:28)
    at Function.ZodError.create (/Users/yury/dev/edge/tutorial/node_modules/zod/lib/src/ZodError.js:66:21)
    at Function.ZodError.fromString (/Users/yury/dev/edge/tutorial/node_modules/zod/lib/src/ZodError.js:71:25)
    at ZodUnion.parse (/Users/yury/dev/edge/tutorial/node_modules/zod/lib/src/parser.js:159:39)
```

after upgrading from 1.0.9 to 1.3.0

**Comment by vriad** [comment]
Hi Yuri,

Sorry about this. I only recently clarified Zod's behavior regarding unknown keys in object schemas. 
The problem is here:

```ts
...
z.object({
  kind: z.literal("error"),
  error: z.tuple([
    z.string(), 
    z.string(), 
    z.object({}) // no unknown keys allowed!
  ]),
}),
...
```
Sorry about this. I only recently clarified Zod's behavior regarding unknown keys in object schemas. Specifically, Zod doesn't allow any unknown keys unless you mark the object as `.nonstrict()`.

But given the sample data you provided, you should use `z.record()` instead, like so:

**Comment by 1st1** [comment]
Yes, your suggestion worked, thank you!

**Comment by 1st1** [comment]
Thanks for the excellent library, I was looking for something like this for ages.
